const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();}
const products=[
{id:1,name:'Red Bull 0.473',price:199,cat:'Напитки',icon:'🥤'},
{id:2,name:'Monster Energy 0.5',price:169,cat:'Напитки',icon:'⚡'},
{id:3,name:'Coca-Cola 0.33',price:99,cat:'Напитки',icon:'🥫'},
{id:4,name:'Haribo Goldbears',price:179,cat:'Сладости',icon:'🍬'},
{id:5,name:'Шоколад',price:149,cat:'Сладости',icon:'🍫'},
{id:6,name:'Чипсы',price:159,cat:'Снеки',icon:'🍟'},
{id:7,name:'Кофе',price:129,cat:'Другое',icon:'☕'},
{id:8,name:'Вода 0.5',price:69,cat:'Напитки',icon:'💧'}];
let cart=JSON.parse(localStorage.getItem('tds38cart')||'{}'); let page='home', filter='';
const save=()=>localStorage.setItem('tds38cart',JSON.stringify(cart)); const count=()=>Object.values(cart).reduce((a,b)=>a+b,0);
function nav(){return `<div class="nav"><button class="${page==='home'?'active':''}" onclick="go('home')"><i>⌂</i>Главная</button><button class="${page==='catalog'?'active':''}" onclick="go('catalog')"><i>▦</i>Каталог</button><button class="${page==='cart'?'active':''}" onclick="go('cart')"><i>🛒</i>Корзина ${count()?`(${count()})`:''}</button><button onclick="go('profile')"><i>♙</i>Профиль</button></div>`}
function card(p){return `<div class="product"><div class="pic">${p.icon}</div><div class="info"><h3>${p.name}</h3><div class="priceRow"><span class="price">${p.price} ₽</span><button class="plus" onclick="add(${p.id})">+</button></div></div></div>`}
function home(){return `<div class="top"><div class="brand"><img src="logo.png"><div><b>TDS38</b><small>магазин • 38 регион</small></div></div><div class="pill">🛒 ${count()}</div></div><div class="hero"><h1>Всё нужное — <span>рядом</span></h1><p>Каталог, актуальные предложения и удобное оформление в Telegram.</p><button class="btn" onclick="go('catalog')">Открыть каталог</button></div><input class="search" placeholder="🔎 Найти товар" oninput="search(this.value)"><div class="quick"><div>🔥<br>Хиты</div><div>✨<br>Новинки</div><div>％<br>Акции</div></div><div class="sectionHead"><h2>Категории</h2><span onclick="go('catalog')">Все →</span></div><div class="cats">${['Напитки','Сладости','Снеки','Другое'].map(c=>`<div class="cat" onclick="category('${c}')"><b>${c}</b><small>Открыть →</small></div>`).join('')}</div><div class="sectionHead"><h2>Популярное</h2></div><div class="products">${products.slice(0,4).map(card).join('')}</div><div class="notice">Первая тестовая версия. Каталог и условия оформления будут заменены на фактические данные магазина.</div>`}
function catalog(){let arr=products.filter(p=>!filter||p.cat===filter||p.name.toLowerCase().includes(filter.toLowerCase()));return `<div class="top"><button class="back" onclick="go('home')">← Назад</button><b>Каталог</b><span>${arr.length} товаров</span></div><input class="search" placeholder="🔎 Поиск" oninput="filter=this.value;render()"><div class="quick">${['Напитки','Сладости','Снеки'].map(c=>`<div onclick="category('${c}')">${c}</div>`).join('')}</div><div class="sectionHead"><h2>${filter||'Все товары'}</h2><span onclick="filter='';render()">Сбросить</span></div><div class="products">${arr.map(card).join('')}</div>`}
function cartPage(){let ids=Object.keys(cart).filter(id=>cart[id]>0);let total=ids.reduce((s,id)=>s+products.find(p=>p.id==id).price*cart[id],0);if(!ids.length)return `<button class="back" onclick="go('home')">← Назад</button><div class="empty"><h2>Корзина пуста</h2><p>Добавь товары из каталога.</p><button class="btn" onclick="go('catalog')">В каталог</button></div>`;return `<button class="back" onclick="go('home')">← Назад</button><div class="sectionHead"><h2>Корзина</h2></div>${ids.map(id=>{let p=products.find(x=>x.id==id);return `<div class="cartItem"><div><b>${p.name}</b><br><small>${p.price} ₽ × ${cart[id]}</small></div><div class="qty"><button onclick="qty(${id},-1)">−</button> ${cart[id]} <button onclick="qty(${id},1)">+</button></div></div>`}).join('')}<div class="total">Итого: ${total} ₽</div><button class="btn wide" onclick="go('checkout')">Продолжить</button>`}
function checkout(){return `<button class="back" onclick="go('cart')">← Корзина</button><div class="sectionHead"><h2>Оформление</h2></div><input class="field" id="name" placeholder="Имя"><input class="field" id="phone" placeholder="Телефон"><input class="field" id="address" placeholder="Адрес / комментарий"><div class="notice">Это демонстрационное оформление. В следующей версии подключим передачу заказа продавцу и статусы.</div><button class="btn wide" onclick="done()">Подтвердить</button>`}
function profile(){return `<button class="back" onclick="go('home')">← Назад</button><div class="empty"><h2>TDS38</h2><p>${tg?.initDataUnsafe?.user?.first_name?`Привет, ${tg.initDataUnsafe.user.first_name}!`:'Профиль покупателя появится после подключения backend.'}</p></div>`}
function render(){document.getElementById('app').innerHTML=`<main class="app">${page==='home'?home():page==='catalog'?catalog():page==='cart'?cartPage():page==='checkout'?checkout():profile()}</main>${page!=='checkout'?nav():''}`}
function go(p){page=p;if(p!=='catalog')filter='';render();scrollTo(0,0)} function add(id){cart[id]=(cart[id]||0)+1;save();tg?.HapticFeedback?.impactOccurred('light');render()} function qty(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];save();render()} function category(c){filter=c;page='catalog';render()} function search(v){filter=v;page='catalog';render()} function done(){alert('Тестовый заказ оформлен. На следующем этапе подключим отправку продавцу.');cart={};save();go('home')} render();
